name: data-science-at-scale
channels:
  - conda-forge
  - defaults
  - conda-forge/label/broken

dependencies:
  - python=3.8
  - bokeh>2.0
  - dask=2.25
  - dask-labextension>=2.0
  - jupyterlab
  - nodejs=14
  - dask-ml
  - numpy
  - pandas
  - pyarrow
  - python-graphviz
  - scikit-learn
  - matplotlib
  - nbserverproxy
  - nomkl
  - h5py
  - requests
  - pytables
  - s3fs
